// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBootstrap(arg1) {
  return window['go']['main']['App']['AddBootstrap'](arg1);
}

export function ConnectPeer(arg1) {
  return window['go']['main']['App']['ConnectPeer'](arg1);
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetNetworkSummary() {
  return window['go']['main']['App']['GetNetworkSummary']();
}

export function GetNodeInfo() {
  return window['go']['main']['App']['GetNodeInfo']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SetCensorshipSimulation(arg1, arg2) {
  return window['go']['main']['App']['SetCensorshipSimulation'](arg1, arg2);
}
