// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddBootstrap(arg1:string):Promise<string>;

export function ConnectPeer(arg1:string):Promise<string>;

export function GetMessages(arg1:string):Promise<Array<main.UIMessage>>;

export function GetMetrics():Promise<string>;

export function GetNetworkSummary():Promise<string>;

export function GetNodeInfo():Promise<main.UINodeInfo>;

export function GetPeers():Promise<Array<main.UIPeer>>;

export function SendMessage(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function SetCensorshipSimulation(arg1:boolean,arg2:number):Promise<string>;
